
package com.projects.webservice.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.6
 * Sun Apr 23 17:29:00 CEST 2017
 * Generated source version: 3.1.6
 */

@XmlRootElement(name = "getItemStructures", namespace = "http://webservice.projects.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getItemStructures", namespace = "http://webservice.projects.com/")

public class GetItemStructures {


}

