package com.projects.tcpserver.webservice.mongodb.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-05-06T20:35:35.822+02:00
 * Generated source version: 3.1.6
 * 
 */
@WebServiceClient(name = "BackendWSService", 
                  wsdlLocation = "http://localhost:8080/BackendWebService/BackendWS?wsdl",
                  targetNamespace = "http://mongodb.webservice.projects.com/") 
public class BackendWSService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://mongodb.webservice.projects.com/", "BackendWSService");
    public final static QName BackendWSPort = new QName("http://mongodb.webservice.projects.com/", "BackendWSPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/BackendWebService/BackendWS?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(BackendWSService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/BackendWebService/BackendWS?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public BackendWSService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public BackendWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BackendWSService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public BackendWSService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public BackendWSService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public BackendWSService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns BackendWS
     */
    @WebEndpoint(name = "BackendWSPort")
    public BackendWS getBackendWSPort() {
        return super.getPort(BackendWSPort, BackendWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BackendWS
     */
    @WebEndpoint(name = "BackendWSPort")
    public BackendWS getBackendWSPort(WebServiceFeature... features) {
        return super.getPort(BackendWSPort, BackendWS.class, features);
    }

}
