
package com.projects.tcpserver.webservice.mongodb.client;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-05-06T20:35:35.792+02:00
 * Generated source version: 3.1.6
 */

@WebFault(name = "CredentialsCheckException", targetNamespace = "http://mongodb.webservice.projects.com/")
public class CredentialsCheckException_Exception extends Exception {
    
    private com.projects.tcpserver.webservice.mongodb.client.CredentialsCheckException credentialsCheckException;

    public CredentialsCheckException_Exception() {
        super();
    }
    
    public CredentialsCheckException_Exception(String message) {
        super(message);
    }
    
    public CredentialsCheckException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public CredentialsCheckException_Exception(String message, com.projects.tcpserver.webservice.mongodb.client.CredentialsCheckException credentialsCheckException) {
        super(message);
        this.credentialsCheckException = credentialsCheckException;
    }

    public CredentialsCheckException_Exception(String message, com.projects.tcpserver.webservice.mongodb.client.CredentialsCheckException credentialsCheckException, Throwable cause) {
        super(message, cause);
        this.credentialsCheckException = credentialsCheckException;
    }

    public com.projects.tcpserver.webservice.mongodb.client.CredentialsCheckException getFaultInfo() {
        return this.credentialsCheckException;
    }
}
